- hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: install git
    yum: name=git state=present
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: get the dockerfile from githib
    git: repo=https://github.com/Mrunmay1312/DevOpsClassCodes.git dest=/tmp/gitrepo
  - name: build dockerfile
    command: chdir=/tmp/gitrepo docker build -t deployimage:ansible .
  - name: run the dockerfile
    command: docker run -itd -P deployimage:ansible
    EXPOSE 8080
